### ISSUE TITLE
Fail command "composer require thujohn/twitter"

### ISSUE THREAD

**Issue by Daoudbk** [thujohn/twitter-l4#65]
- Installation request for thujohn/twitter ~1.2 -> satisfiable by thujohn/tw
itter[1.2.0].
    - Conclusion: remove laravel/framework v5.0.13
    - thujohn/twitter 1.2.0 requires illuminate/support 4.x -> satisfiable by il
luminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6 ......

    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.0.13
    - don't install illuminate/support v4.0.1|don't install laravel/framework v5.0.13
    ............

Installation failed, reverting ./composer.json to its original content.

Any help please in this error !!!

**Comment by matriphe** [comment]
try use version `2.0.x-dev` on composer.

**Comment by cre8** [comment]
> composer require thujohn/twitter ~2.0.x-dev

throws another error:
> The requested package thujohn/twitter could not be found in any version, there may be a typo in the package name.

**Comment by matriphe** [comment]
This work only for Laravel 5. Open `composer.json` and then add this `"thujohn/twitter": "2.0.x-dev"` in `require` section. Do `composer update` from console.

**Comment by cre8** [comment]
Nice, worked this way :)

**Comment by Daoudbk** [comment]
thanks for all reply, i already found it :)
